name: 'Update package file'
description: 'update version in package.json and package-lock.json'
inputs:
  ref:
    description: 'Branch to update files on'
    required: true
  packages-to-update:
    description: 'List of packages whos versions need updating'
runs:
  using: 'node12'
  main: 'dist/index.js'